class CfgPatches {
	class 16AA_crate_main {
		requiredaddons[] = {"16aa_crates_a3"};
		requiredversion = 0.1;
		units[] = {"16AA_crate_main"};
		weapons[] = {};
		magazines[] = {};
	};
};

class CfgVehicles {
	class 16aa_crate_empty_main;

	class 16AA_crate_main : 16aa_crate_empty_main {
		scope = public;
		author = "Adams & Beazley";
		displayName = "Main";
		vehicleClass = "16aa_Crates";
		class TransportWeapons {
            MACRO_ADDWEAPON(16aa_l85a2_ris_e,50);
            MACRO_ADDWEAPON(16aa_l85a2_ugl_ladder_e,25);
            MACRO_ADDWEAPON(16aa_l22_e,20);
            MACRO_ADDWEAPON(16aa_l85a2_ris_e,50);
            MACRO_ADDWEAPON(16aa_l129a1_HG_Bipod,20);
            MACRO_ADDWEAPON(16aa_l110a2_mk1,25);
            MACRO_ADDWEAPON(16AA_L7A2,25);
            MACRO_ADDWEAPON(16aa_M1014_breacher,15);
            MACRO_ADDWEAPON(16AA_G17,50);
            MACRO_ADDWEAPON(16aa_AT4CSHP,50);
            MACRO_ADDWEAPON(launch_NLAW_F,30);
            MACRO_ADDWEAPON(16aa_Stinger_Launcher,15);
            MACRO_ADDWEAPON(16aa_Javelin_Launcher,15);
        };
        class TransportItems {
            MACRO_ADDITEM(16aa_optic_LDS,10);
            MACRO_ADDITEM(16aa_optic_LDS_2d,10);
            MACRO_ADDITEM(16aa_optic_LDS_pip,10);
            MACRO_ADDITEM(RH_m145,10);
            MACRO_ADDITEM(16aa_HMNVS,100);
            MACRO_ADDITEM(optic_NVS,35);
            MACRO_ADDITEM(optic_TWS,15);
            MACRO_ADDITEM(optic_TWS_MG,5);
            MACRO_ADDITEM(16aa_LLM_MK3_FL,40);
            MACRO_ADDITEM(RH_ta648,10);
            MACRO_ADDITEM(tf_anprc152,50);
            MACRO_ADDITEM(ACE_CableTie,50);
            MACRO_ADDITEM(ACE_bodyBag,30);
            MACRO_ADDITEM(ACE_Clacker,20);
            MACRO_ADDITEM(ACE_M26_Clacker,5);
            MACRO_ADDITEM(ItemMap,50);
            MACRO_ADDITEM(ItemCompass,50);
            MACRO_ADDITEM(B_UavTerminal,5);
            MACRO_ADDITEM(Laserdesignator,10);
            MACRO_ADDITEM(Laserbatteries,30);
            MACRO_ADDITEM(ACE_M84,20);
            MACRO_ADDITEM(ACE_Vector,15);
            MACRO_ADDITEM(ACE_MapTools,10);
            MACRO_ADDITEM(ACE_packingBandage,150);
            MACRO_ADDITEM(ACE_fieldDressing,150);
            MACRO_ADDITEM(ACE_morphine,100);
            MACRO_ADDITEM(ACE_epinephrine,100);
            MACRO_ADDITEM(ACE_atropine,100);
            MACRO_ADDITEM(ACE_salineIV,100);
            MACRO_ADDITEM(ACE_tourniquet,100);
            MACRO_ADDITEM(ACE_quikclot,100);
            MACRO_ADDITEM(16aa_G_Tactical_Clear,20);
            MACRO_ADDITEM(16aa_G_Tactical_Clear_ACE,20);
            MACRO_ADDITEM(16aa_G_Tactical_Yellow,20);
            MACRO_ADDITEM(16aa_G_Tactical_Yellow_ACE,20);
            MACRO_ADDITEM(16aa_G_Tactical_Black,20);
            MACRO_ADDITEM(16aa_G_Tactical_Black_ACE,20);
        };
        class TransportMagazines{
        	MACRO_ADDMAGAZINE(30Rnd_556x45_Stanag,400);
        	MACRO_ADDMAGAZINE(20Rnd_762x51_Mag,150);
        	MACRO_ADDMAGAZINE(16AA_17Rnd_9x19_g17,80);
        	MACRO_ADDMAGAZINE(sti_200Rnd_556x45,200);
        	MACRO_ADDMAGAZINE(16aa_150Rnd_762x51_box_gpmg,100);
        	MACRO_ADDMAGAZINE(16aa_8Rnd_12Gauge_Pellets,100);
        	MACRO_ADDMAGAZINE(16aa_8Rnd_12Gauge_Slug,100);
        	MACRO_ADDMAGAZINE(1Rnd_HE_Grenade_shell,200);
        	MACRO_ADDMAGAZINE(1Rnd_SmokeYellow_Grenade_shell,100);
        	MACRO_ADDMAGAZINE(1Rnd_SmokeBlue_Grenade_shell,100);
        	MACRO_ADDMAGAZINE(1Rnd_SmokeRed_Grenade_shell,100);
        	MACRO_ADDMAGAZINE(SmokeShellRed,100);
        	MACRO_ADDMAGAZINE(SmokeShellYellow,100);
        	MACRO_ADDMAGAZINE(SmokeShellBlue,100);
        	MACRO_ADDMAGAZINE(chemlight_blue,100);
        	MACRO_ADDMAGAZINE(chemlight_green,100);
        	MACRO_ADDMAGAZINE(B_IR_Grenade,100);
        	MACRO_ADDMAGAZINE(ACE_M84,150);
        	MACRO_ADDMAGAZINE(SatchelCharge_Remote_Mag,20);
        	MACRO_ADDMAGAZINE(DemoCharge_Remote_Mag,60);
        	MACRO_ADDMAGAZINE(ClaymoreDirectionalMine_Remote_Mag,20);
        	MACRO_ADDMAGAZINE(ATMine_Range_Mag,20);
        	MACRO_ADDMAGAZINE(16AA_HandGrenade,100);
        	MACRO_ADDMAGAZINE(16aa_Stinger_M,50);
        	MACRO_ADDMAGAZINE(16aa_javelin_m,50);
        };
    };
};