	class 16AA_crate_section: 16aa_crate_empty {
		author = "3LSR";
		displayName = "Section";
		vehicleClass = "16aa_Crates";
		class TransportWeapons {
            MACRO_ADDWEAPON(16aa_l85a2_ris_e,2);
            MACRO_ADDWEAPON(16aa_l85a2_ugl_ladder_e_r,2);
            MACRO_ADDWEAPON(16aa_l129a1_HG_Bipod,1);
            MACRO_ADDWEAPON(16aa_l110a2_mk1,2);
            MACRO_ADDWEAPON(16AA_L7A2,1);
            MACRO_ADDWEAPON(16AA_G17,3);
            MACRO_ADDWEAPON(16aa_AT4CSHP,8);
            MACRO_ADDWEAPON(launch_NLAW_F,2);
        };
        class TransportItems {
            MACRO_ADDITEM(tf_anprc152,5);
            MACRO_ADDITEM(16aa_optic_LDS,10);
            MACRO_ADDITEM(16aa_optic_LDS_2d,10);
            MACRO_ADDITEM(16aa_optic_LDS_pip,10);
            MACRO_ADDITEM(16aa_HMNVS,10);
            MACRO_ADDITEM(optic_NVS,4);
            MACRO_ADDITEM(16aa_LLM_MK3_LZ,10);
            MACRO_ADDITEM(RH_ta648,1);
            MACRO_ADDITEM(optic_TWS,1);
            MACRO_ADDITEM(ACE_MX2A,1);
            MACRO_ADDITEM(ACE_MapTools,10);
            MACRO_ADDITEM(ACE_CableTie,20);
            MACRO_ADDITEM(ACE_bodyBag,10);
            MACRO_ADDITEM(ACE_M26_Clacker,15);
            MACRO_ADDITEM(16aa_G_Tactical_Clear,10);
            MACRO_ADDITEM(16aa_G_Tactical_Clear_ACE,10);
            MACRO_ADDITEM(16aa_G_Tactical_Yellow,10);
            MACRO_ADDITEM(16aa_G_Tactical_Yellow_ACE,10);
            MACRO_ADDITEM(16aa_G_Tactical_Black,10);
            MACRO_ADDITEM(16aa_G_Tactical_Black_ACE,10);
        };
        class TransportMagazines{
        	MACRO_ADDMAGAZINE(30Rnd_556x45_Stanag,60);
        	MACRO_ADDMAGAZINE(20Rnd_762x51_Mag,30);
        	MACRO_ADDMAGAZINE(sti_200Rnd_556x45,20);
        	MACRO_ADDMAGAZINE(16aa_150Rnd_762x51_box_gpmg,20);
        	MACRO_ADDMAGAZINE(16AA_17Rnd_9x19_g17,10);
        	MACRO_ADDMAGAZINE(1Rnd_HE_Grenade_shell,30);
        	MACRO_ADDMAGAZINE(16AA_HandGrenade,30);
			MACRO_ADDMAGAZINE(16aa_Smoke_Screening_White,30);
			MACRO_ADDMAGAZINE(SmokeShellYellow,30);
        	MACRO_ADDMAGAZINE(16aa_Smoke_Signalling_Red,30);
			MACRO_ADDMAGAZINE(16aa_Smoke_Signalling_Blue,30);
			MACRO_ADDMAGAZINE(16aa_Smoke_Signalling_Green,30);
			MACRO_ADDMAGAZINE(16aa_Smoke_Signalling_Orange,30);
			MACRO_ADDMAGAZINE(16aa_Smoke_Signalling_Purple,30);
        	MACRO_ADDMAGAZINE(1Rnd_SmokeRed_Grenade_shell,20);
        	MACRO_ADDMAGAZINE(DemoCharge_Remote_Mag,6);
        	MACRO_ADDMAGAZINE(ClaymoreDirectionalMine_Remote_Mag,3);
        	MACRO_ADDMAGAZINE(ATMine_Range_Mag,5);
        	MACRO_ADDMAGAZINE(ACE_M84,25);
        };
	};